        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 28 14:25:28 2014
        MODULE FREEFLIGHTTIME__genmod
          INTERFACE 
            SUBROUTINE FREEFLIGHTTIME(DT,GAMMAT)
              REAL(KIND=8) :: DT
              REAL(KIND=8) :: GAMMAT
            END SUBROUTINE FREEFLIGHTTIME
          END INTERFACE 
        END MODULE FREEFLIGHTTIME__genmod
