        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 28 14:25:28 2014
        MODULE PSEUDO_SCATTERINGRATE__genmod
          INTERFACE 
            SUBROUTINE PSEUDO_SCATTERINGRATE
            END SUBROUTINE PSEUDO_SCATTERINGRATE
          END INTERFACE 
        END MODULE PSEUDO_SCATTERINGRATE__genmod
